
INSERT INTO USERS (EMAIL,PSEUDO,PASSWORD,POINTS,PP,STATUS,DATES)
VALUES ( 'test@test.fr', 'jacky', '123', 1, 'sex', 1, '2019-08-15');
INSERT INTO USERS (EMAIL,PSEUDO,PASSWORD,POINTS,PP,STATUS,DATES)
VALUES ( 'tet@test.fr', 'jacky', '123', 1, 'sex', 1, '2019-08-15');
INSERT INTO USERS (EMAIL,PSEUDO,PASSWORD,POINTS,PP,STATUS,DATES)
VALUES ( 'tst@test.fr', 'jacky', '123', 1, 'sex', 1, '2019-08-15');
